// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Postgres.Context.DBContext;

#nullable disable

namespace ActyIn.Migrations
{
    [DbContext(typeof(NpgsqlContext))]
    [Migration("20231226212632_V100")]
    partial class V100
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Postgres.Context.Entities.ApplicationFileEntity", b =>
                {
                    b.Property<int>("SportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SportId"));

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SportName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SportId");

                    b.ToTable("ApplicationImages");
                });

            modelBuilder.Entity("Postgres.Context.Entities.AthletesEntity", b =>
                {
                    b.Property<int>("AthletesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AthletesId"));

                    b.Property<string>("Address")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FavoriteActivity")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<int>("PostalCode")
                        .HasColumnType("integer");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("AthletesId");

                    b.ToTable("AthletesInfo");
                });

            modelBuilder.Entity("Postgres.Context.Entities.BookingEntity", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BookingId"));

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("boolean");

                    b.HasKey("BookingId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Postgres.Context.Entities.ChosenActivityEntity", b =>
                {
                    b.Property<int>("ChosenActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChosenActivityId"));

                    b.Property<int?>("AthletesEntityAthletesId")
                        .HasColumnType("integer");

                    b.Property<string>("ChosenActivityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfActivity")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("MatchModelEntityMatchModelId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("ChosenActivityId");

                    b.HasIndex("AthletesEntityAthletesId");

                    b.HasIndex("MatchModelEntityMatchModelId");

                    b.ToTable("ChooseActivityInfo");
                });

            modelBuilder.Entity("Postgres.Context.Entities.FileEntity", b =>
                {
                    b.Property<int>("AthleteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AthleteId"));

                    b.Property<string>("AthleteName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AthleteId");

                    b.ToTable("AthleteImageProfile");
                });

            modelBuilder.Entity("Postgres.Context.Entities.MatchModelEntity", b =>
                {
                    b.Property<int>("MatchModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MatchModelId"));

                    b.Property<int?>("BookingEntityBookingId")
                        .HasColumnType("integer");

                    b.Property<int>("ChosenActivityId")
                        .HasColumnType("integer");

                    b.Property<bool>("LikeThePotentialAthlete")
                        .HasColumnType("boolean");

                    b.HasKey("MatchModelId");

                    b.HasIndex("BookingEntityBookingId");

                    b.ToTable("MatchModels");
                });

            modelBuilder.Entity("Postgres.Context.Entities.ChosenActivityEntity", b =>
                {
                    b.HasOne("Postgres.Context.Entities.AthletesEntity", null)
                        .WithMany("ChosenActivities")
                        .HasForeignKey("AthletesEntityAthletesId");

                    b.HasOne("Postgres.Context.Entities.MatchModelEntity", null)
                        .WithMany("ChosenActivities")
                        .HasForeignKey("MatchModelEntityMatchModelId");
                });

            modelBuilder.Entity("Postgres.Context.Entities.MatchModelEntity", b =>
                {
                    b.HasOne("Postgres.Context.Entities.BookingEntity", "BookingEntity")
                        .WithMany()
                        .HasForeignKey("BookingEntityBookingId");

                    b.Navigation("BookingEntity");
                });

            modelBuilder.Entity("Postgres.Context.Entities.AthletesEntity", b =>
                {
                    b.Navigation("ChosenActivities");
                });

            modelBuilder.Entity("Postgres.Context.Entities.MatchModelEntity", b =>
                {
                    b.Navigation("ChosenActivities");
                });
#pragma warning restore 612, 618
        }
    }
}
